const DUAS = [
  { id: 1, category: "Waking Up", title: "Upon waking up",
    arabic: "الْحَمْدُ للَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا، وَإِلَيْهِ النُّشُورُ",
    transliteration: "Alhamdu lillahil-lathee ahyana ba'da ma amatana wa-ilayhin-nushoor.",
    translation: "All praise is for Allah who gave us life after having taken it from us, and unto Him is the resurrection.",
    repeat: 1 },
  { id: 2, category: "Getting Dressed", title: "When putting on clothes",
    arabic: "الْحَمْدُ للَّهِ الَّذِي كَسَانِي هَذَا وَرَزَقَنِيهِ مِنْ غَيْرِ حَوْلٍ مِنِّي وَلاَ قُوَّةٍ",
    transliteration: "Alhamdu lillahil-lathee kasanee hatha warazaqaneehi min ghayri hawlin minnee wala quwwah.",
    translation: "All praise is for Allah who has clothed me with this garment and provided it for me, with no power nor might from myself.",
    repeat: 1 },
  { id: 3, category: "Home", title: "When leaving the home",
    arabic: "بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلاَّ بِاللَّهِ",
    transliteration: "Bismil-lah, tawakkaltu 'alal-lah, wala hawla wala quwwata illa billah.",
    translation: "In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.",
    repeat: 1 },
  { id: 4, category: "Home", title: "When entering the home",
    arabic: "بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى اللَّهِ رَبِّنَا تَوَكَّلْنَا",
    transliteration: "Bismil-lahi walajna, wabismil-lahi kharajna, wa'ala rabbina tawakkalna.",
    translation: "In the name of Allah we enter and in the name of Allah we leave, and upon our Lord we place our trust.",
    repeat: 1 },
  { id: 5, category: "Mosque & Prayer Call", title: "Upon hearing the Athan",
    arabic: "لاَ حَوْلَ وَلاَ قُوَّةَ إِلاَّ بِاللَّهِ",
    transliteration: "La hawla wala quwwata illa billah.",
    translation: "There is no might nor power except with Allah. (Said in place of repeating the 'Hayya 'ala' phrases)",
    repeat: 1 },
  { id: 6, category: "Before Sleeping", title: "Before sleeping",
    arabic: "بِاسْمِكَ رَبِّي وَضَعْتُ جَنْبِي، وَبِكَ أَرْفَعُهُ، فَإِنْ أَمْسَكْتَ نَفْسِي فَارْحَمْهَا، وَإِنْ أَرْسَلْتَهَا فَاحْفَظْهَا",
    transliteration: "Bismika rabbee wada'tu janbee wabika arfa'uh, fa-in amsakta nafsee farhamha, wa-in arsaltaha fahfathha.",
    translation: "In Your name my Lord, I lie down and in Your name I rise, so if You should take my soul then have mercy upon it, and if You should return my soul then protect it.",
    repeat: 1 },
  { id: 7, category: "Morning & Evening", title: "Morning remembrance",
    arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لاَ إِلَهَ إلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ",
    transliteration: "Asbahna wa-asbahal-mulku lillah walhamdu lillah la ilaha illal-lah, wahdahu la shareeka lah.",
    translation: "We have reached the morning and at this very time unto Allah belongs all sovereignty, and all praise is for Allah. None has the right to be worshipped except Allah, alone, without partner.",
    repeat: 1 },
  { id: 8, category: "Morning & Evening", title: "Seeking Allah's sufficiency",
    arabic: "حَسْبِيَ اللَّهُ لاَ إِلَهَ إِلاَّ هُوَ عَلَيهِ تَوَكَّلتُ وَهُوَ رَبُّ الْعَرْشِ الْعَظِيمِ",
    transliteration: "Hasbiyal-lahu la ilaha illa huwa, 'alayhi tawakkalt, wahuwa rabbul-'arshil-'atheem.",
    translation: "Allah is Sufficient for me, none has the right to be worshipped except Him, upon Him I rely and He is Lord of the exalted throne.",
    repeat: 7 },
  { id: 9, category: "Morning & Evening", title: "Seeking forgiveness",
    arabic: "أَسْتَغْفِرُ اللَّهَ وَأَتُوبُ إِلَيْهِ",
    transliteration: "Astaghfirullaaha wa atoobu ilayhi.",
    translation: "I seek Allah's forgiveness and I turn to Him in repentance.",
    repeat: 100 },
  { id: 10, category: "Prayer (Salah)", title: "Between two prostrations",
    arabic: "رَبِّ اغْفِرْ لِي، رَبِّ اغْفِرْ لِي",
    transliteration: "Rabbigh-fir lee, rabbigh-fir lee.",
    translation: "My Lord forgive me, My Lord forgive me.",
    repeat: 1 },
  { id: 11, category: "Waking Up", title: "Fuller morning remembrance",
    arabic: "لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَريكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ، رَبِّ اغْفرْ لِي",
    transliteration: "La ilaha illal-lahu wahdahu la shareeka lah, lahul-mulku walahul-hamd, wahuwa 'ala kulli shay-in qadeer. Rabbigh-fir lee.",
    translation: "None has the right to be worshipped except Allah, alone without associate, to Him belongs sovereignty and praise and He is over all things wholly capable. O my Lord forgive me.",
    repeat: 1 },
  { id: 12, category: "Restroom", title: "Entering the restroom",
    arabic: "بِسْمِ اللَّهِ اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْخُبْثِ وَالْخَبائِث",
    transliteration: "Bismil-lah, allahumma innee a'oothu bika minal-khubthi wal-khaba-ith.",
    translation: "In the name of Allah. O Allah, I take refuge with You from all evil and evil-doers.",
    repeat: 1 },
  { id: 13, category: "Restroom", title: "Leaving the restroom",
    arabic: "غُفْرَانَكَ",
    transliteration: "Ghufranak.",
    translation: "I ask You (Allah) for forgiveness.",
    repeat: 1 },
  { id: 14, category: "Ablution (Wudu)", title: "Before performing ablution",
    arabic: "بِسْمِ اللَّهِ",
    transliteration: "Bismil-lah.",
    translation: "In the name of Allah.",
    repeat: 1 },
  { id: 15, category: "Ablution (Wudu)", title: "Upon completing ablution",
    arabic: "أَشْهَدُ أَنْ لاَ إِلَهَ إِلاَّ اللَّهُ وَحْدَهُ لاَ شَرِيكَ لَهُ وَأَشْهَدُ أَنَّ مُحَمَّداً عَبْدُهُ وَرَسُولُهُ",
    transliteration: "Ash-hadu an la ilaha illal-lahu wahdahu la shareeka lah, wa-ash-hadu anna Muhammadan 'abduhu warasooluh.",
    translation: "I bear witness that none has the right to be worshipped except Allah, alone without partner, and I bear witness that Muhammad is His slave and Messenger.",
    repeat: 1 },
  { id: 16, category: "Mosque & Prayer Call", title: "Going to the mosque",
    arabic: "اللّهُـمَّ اجْعَـلْ فِي قَلْبـي نُوراً وَفي لِسَـانِي نُوراً وَفِي سَمْعِي نُوراً وَفِي بَصَرِيِ نُوراً",
    transliteration: "Allaahummaj'al fee qalbee nooran, wa fee lisaanee nooran, wa fee sam'ee nooran, wa fee basaree nooran.",
    translation: "O Allah, place within my heart light, and upon my tongue light, and within my ears light, and within my eyes light.",
    repeat: 1 },
  { id: 17, category: "Mosque & Prayer Call", title: "Entering the mosque",
    arabic: "أَعُوذُ بِاللَّهِ العَظِيمِ وَبِوَجْهِهِ الْكَرِيمِ وَسُلْطَانِهِ الْقَدِيمِ مِنَ الشَّيْطَانِ الرَّجِيمِ. اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ",
    transliteration: "A'oothu billahil-'atheem wabiwajhihil-kareem wasultanihil-qadeem minash-shaytanir-rajeem, allahumma iftah lee abwaba rahmatik.",
    translation: "I take refuge with Allah, The Supreme, from the accursed devil. O Allah, open the gates of Your mercy for me.",
    repeat: 1 },
  { id: 18, category: "Mosque & Prayer Call", title: "Leaving the mosque",
    arabic: "اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِك، اللَّهُمَّ اعْصِمْنِي مِنَ الشَّيْطَانِ الرَّجِيمِ",
    transliteration: "Allahumma innee as-aluka min fadlik, allahumma i'simnee minash-shaytanir-rajeem.",
    translation: "O Allah, I ask You from Your favour. O Allah, guard me from the accursed devil.",
    repeat: 1 },
  { id: 19, category: "Prayer (Salah)", title: "Opening supplication of the prayer",
    arabic: "سُبْحَانَكَ اللَّهُمَّ وَبِحَمْدِكَ، وَتَبارَكَ اسْمُكَ، وَتَعَالَى جَدُّكَ، وَلاَ إِلَهَ غَيْرُكَ",
    transliteration: "Subhanakal-lahumma wabihamdika watabarakas-muka wata'ala jadduka wala ilaha ghayruk.",
    translation: "How perfect You are O Allah, and I praise You. Blessed be Your name, and lofty is Your position, and none has the right to be worshipped except You.",
    repeat: 1 },
  { id: 20, category: "Prayer (Salah)", title: "During Ruku' (bowing)",
    arabic: "سُبْحانَ رَبِّيَ الْعَظِيمِ",
    transliteration: "Subhana rabbiyal-'atheem.",
    translation: "How perfect my Lord is, The Supreme.",
    repeat: 3 },
  { id: 21, category: "Prayer (Salah)", title: "Rising from Ruku'",
    arabic: "سَمِعَ اللَّهُ لِمَنْ حَمِدَهُ، رَبَّنَا وَلَكَ الْحَمْدُ",
    transliteration: "Sami'al-lahu liman hamidah. Rabbana walakal-hamd.",
    translation: "May Allah answer he who praises Him. Our Lord, for You is all praise.",
    repeat: 1 },
  { id: 22, category: "Prayer (Salah)", title: "During Sujood (prostration)",
    arabic: "سُبْحَانَ رَبِّيَ الأَعْلَى",
    transliteration: "Subhana rabbiyal-a'la.",
    translation: "How perfect my Lord is, The Most High.",
    repeat: 3 },
  { id: 23, category: "Prayer (Salah)", title: "At-Tashahhud (sitting in prayer)",
    arabic: "التَّحِيَّاتُ لِلَّهِ، وَالصَّلَواتُ، وَالطَّيِّباتُ، السَّلاَمُ عَلَيْكَ أَيُّهَا النَّبِيُّ وَرَحْمَةُ اللَّهِ وَبَرَكَاتُهُ",
    transliteration: "Attahiyyatu lillahi wassalawatu wattayyibat, assalamu 'alayka ayyuhan-nabiyyu warahmatul-lahi wabarakatuh.",
    translation: "All greetings, prayers and good deeds are for Allah. Peace and the mercy and blessings of Allah be upon you O Prophet.",
    repeat: 1 },
  { id: 24, category: "Prayer (Salah)", title: "Blessings on the Prophet",
    arabic: "اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ، وَعَلَى آلِ مُحَمَّدٍ، كَمَا صَلَّيتَ عَلَى إِبْرَاهِيمَ",
    transliteration: "Allahumma salli 'ala Muhammad, wa-'ala ali Muhammad, kama sallayta 'ala Ibraheem.",
    translation: "O Allah, send prayers upon Muhammad and the followers of Muhammad, just as You sent prayers upon Ibraheem.",
    repeat: 1 },
  { id: 25, category: "Prayer (Salah)", title: "Before ending the prayer",
    arabic: "اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنْ عَذَابِ الْقَبْرِ، وَمِنْ عَذَابِ جَهَنَّمَ",
    transliteration: "Allahumma innee a'oothu bika min 'athabil-qabr, wamin 'athabi jahannam.",
    translation: "O Allah, I take refuge in You from the punishment of the grave, and from the torment of the Fire.",
    repeat: 1 },
  { id: 26, category: "Morning & Evening", title: "Declaration of contentment",
    arabic: "رَضِيتُ بِاللَّهِ رَبَّاً، وَبِالْإِسْلاَمِ دِيناً، وَبِمُحَمَّدٍ نَبِيّاً",
    transliteration: "Radeetu billahi rabban wabil-islami deenan wabiMuhammadin nabiyya.",
    translation: "I am pleased with Allah as a Lord, and Islam as a religion, and Muhammad as a Prophet.",
    repeat: 3 },
  { id: 27, category: "Morning & Evening", title: "Seeking Allah's help in every affair",
    arabic: "يَا حَيُّ يَا قَيُّومُ بِرَحْمَتِكَ أَسْتَغيثُ أَصْلِحْ لِي شَأْنِيَ كُلَّهُ",
    transliteration: "Ya hayyu ya qayyoom, birahmatika astagheeth, aslih lee sha'nee kullah.",
    translation: "O Ever Living, O Self-Subsisting and Supporter of all, by Your mercy I seek assistance, rectify for me all of my affairs.",
    repeat: 1 },
  { id: 28, category: "Before Sleeping", title: "Tasbih before sleep",
    arabic: "سُبْحَانَ اللَّهِ (ثلاثاً وثلاثين) وَالْحَمْدُ لِلَّهِ (ثلاثاً وثلاثين) وَاللَّهُ أَكْبَرُ (أربعاً وثلاثينَ)",
    transliteration: "Subhanal-lah (33 times), Alhamdu lillah (33 times), Allahu akbar (34 times).",
    translation: "How Perfect Allah is (33 times). All praise is for Allah (33 times). Allah is the greatest (34 times).",
    repeat: 1 },
  { id: 29, category: "Before Sleeping", title: "Trusting Allah with one's soul",
    arabic: "اللَّهُمَّ أَسْلَمْتُ نَفْسِي إِلَيْكَ، وَفَوَّضْتُ أَمْرِي إِلَيْكَ، وَوَجَّهْتُ وَجْهِي إِلَيْكَ",
    transliteration: "Allahumma aslamtu nafsee ilayk, wafawwadtu amree ilayk, wawajjahtu wajhee ilayk.",
    translation: "O Allah, I submit my soul unto You, and I entrust my affair unto You, and I turn my face towards You.",
    repeat: 1 },
  { id: 30, category: "Getting Dressed", title: "For someone wearing new clothes",
    arabic: "اِلْبَسْ جَدِيداً وَعِشْ حَمِيداً وَمُتْ شَهِيداً",
    transliteration: "Ilbas jadeedan wa'ish hameedan wamut shaheedan.",
    translation: "Wear anew, live commendably, and pass away in a state pleasing to Allah.",
    repeat: 1 },
];
